version: '3.1'

services:
  backend-challenge_app:
    container_name: backend-challenge_app
    hostname: backend-challenge_app
    image: node:16
    working_dir: /usr/app/app
    entrypoint: [ "bash", "-c" ]
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/app/app:rw
    command:
      - |
        npm install
        npm install nodemon -g
        nodemon index.js
  backend-challenge_db:
    container_name: backend-challenge_db
    hostname: backend-challenge_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: backendChallenge
    ports:
      - "33066:3306"
    volumes:
      - ./db:/var/lib/mysql
    command: '--authentication_policy=mysql_native_password'
